using RT.Util.Lingo;

namespace EsotericIDE
{
    [LingoStringClass]
    sealed partial class AboutBoxTranslation
    {
#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString AboutBox = "About Esoteric IDE";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString lblCredits = "Credits:\r\n    Programming: Timwi";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString btnOK = "OK";
    }

    [LingoStringClass]
    sealed partial class MainformTranslation
    {
#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString Mainform = "Esoteric IDE";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString lblSource = "Source &code:\t";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString ctMenu = "Main menu";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString mnuFile = "&File";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miNew = "&New";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miOpen = "&Open...";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miSave = "&Save";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miSaveAs = "Save &As...";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miExit = "E&xit";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString mnuView = "&View";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miSourceFont = "&Source Font...";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miOutputFont = "&Output Font...";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString mnuInsert = "&Insert";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString mnuDebug = "&Debug";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miRun = "&Run";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miStopDebugging = "&Stop debugging";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miStep = "S&tep";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miRunToCursor = "Run to &cursor";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miGoToCurrentInstruction = "&Go to current instruction";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miInput = "&Input...";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miClearInput = "C&lear input";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString optionsToolStripMenuItem = "&Options";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miSaveWhenRun = "&Save when Run";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString mnuHelp = "&Help";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString miAbout = "&About...";
    }
}
